GROUP_ID=io.github.hezd
ARTIFACT_ID=dns-resolver
VERSION_NAME=1.0.0
signing.keyId=399BE563
signing.password=leslie41.
signing.secretKeyRingFile=/Users/hezd/.gnupg/secring.gpg
MAVEN_PRO_USERNAME=6m4rxx
MAVEN_PRO_PASSWORD=HMhw5MJLeUJxzizo2bPEil5Pjdn1jBalb
POM_DESCRIPTION=dns-java
POM_SCM_GIT_BRANCH=